### ISSUE TITLE
Subscribing to a channel

### ISSUE THREAD

**Issue by iRonin** [ascorbic/socket-io-actionscript#2]
Hello,

Is it possible to subscribe to a channel?
Could you please provide an example?

Thanks!

**Comment by ascorbic** [comment]
Hi,
There's an example in the README. Does that not work for you?

Matt

**Comment by iRonin** [comment]
It works partially - I can see that the client connects and disconnects - nothing is received by juggernaut server.
I also don't know yet how to subscribe to a channel.

**Comment by ascorbic** [comment]
This is just a socket.io client: it doesn't know the Juggernaut protocol, so you'll need to implement the pub/sub stuff yourself. It shouldn't be too hard to port that from javascript. From what I can see, Juggernaut is just sending objects of the form {type: 'subscribe', channel: 'foo'} to subscribe. Look at the source here: https://github.com/maccman/juggernaut/blob/master/public/juggernaut.js

If you do implement it, it would be great i you could contribute the code back.

**Comment by iRonin** [comment]
I'm connecting with your client to a Socket.io server, the client is connecting but the server does not receive anything I am sending.

I'm getting only this:

```
4 Mar 16:46:26 - Initializing client with transport "flashsocket"
4 Mar 16:46:26 - Client 573147515533492 connected
4 Mar 16:46:44 - Client 573147515533492 disconnected
```

The client disconnects after first send.
